name: Publish to npm on Version Commit

on:
  push:
    tags:
      - 'v*'  # Triggers on any tag starting with 'v'

jobs:
  publish:
    if: contains(github.event.head_commit.message, 'version')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm install

      - name: Authenticate with npm
        run: npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
        env:
          NODE_AUTH_TOKEN: ${{ secrets.OPENMATE_PUBLISH_TOKEN }}

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.OPENMATE_PUBLISH_TOKEN }}
